### ISSUE TITLE
[Q] `String#{trimStart, trimEnd}` and `String#{trimLeft, trimRigth}` equality

### ISSUE THREAD

**Issue by zloirock** [sebmarkbage/ecmascript-string-left-right-trim#4]
Is it the same functions? If the same - which names they should have?

``` js
String.prototype.trimStart === String.prototype.trimLeft; // ???
String.prototype.trimStart.name; // ???
String.prototype.trimLeft.name; // ???
```

**Comment by ljharb** [comment]
That's a good question. The options are either:
- they are `!==`
- they are `===` and their names are `trimStart`/`trimEnd`
- they are `===` and their names are `trimLeft`/`trimRight`

I think that the easiest as well as the one that ends up with the preferred names is the first option - where they are different functions but both call the same internal abstract operation.

**Comment by zloirock** [comment]
The first way the easiest, but currently in the spec if functions do the same - it's the same  functions. Simple example - `Set#{keys, values, @@iterator}`.

**Comment by ljharb** [comment]
That's a good point. Based on that pattern, it'd be one of the second two - probably the third option for easier legacy compat.

**Comment by zloirock** [comment]
Agree.

@sebmarkbage ?

**Comment by claudepache** [comment]
FWIW, `Date.prototype.toGMTString === Date.prototype.toUTCString` is **true** (with name "toUTCString") in Firefox and ES2015, but **false** in Chrome, Safari (with names "toGMTString" and "toUTCString") and IE (without name).

If we seek spec consistency with that precedent, the option "=== w/ names trimStart/trimEnd" should be picked. Also, I don’t think there is much compat issue around the name of these functions, since functions in IE11 have no name.

Anyway, personally I don’t care, as long as the "official" function (`trimStart`) gets the "correct" name (`"trimStart"`).

**Comment by ljharb** [comment]
The current spec makes `trimStart` and `trimEnd` be the canonical functions with the appropriate name, which are `===` to `trimLeft`/`trimRight`.

**Comment by evilpie** [comment]
I think we can close this for now. If this for some reason is causing concern at the meeting we can reopen the issue.
